### ISSUE TITLE
锁定亮度与对比度，好像labelme 还是labelimg 或者优化版，有这个功能

### ISSUE THREAD

**Issue by aiyou9** [CVHub520/X-AnyLabeling#104]

**Comment by CVHub520** [comment]
Hi, @aiyou9 :
The feature you mentioned, which locks brightness and contrast, is now supported. You can experience this by updating the source code. However, it's important to note that when the auto-save mode is enabled, it may slow down image loading since it requires rendering for each frame. So, please use it with caution.

If you have any more questions or need further assistance, feel free to reach out.

Best regards,
CVHub

**Comment by aiyou9** [comment]
I test， this is   a  great work
