### ISSUE TITLE
Attribute assignment bug

### ISSUE THREAD

**Issue by zhangpzh** [CVHub520/X-AnyLabeling#135]
Hello,  @CVHub520.  I also encounter similar issues in attribute editing as @Sean27oz did.  I am using the Linux release GPU on Ubuntu 20.04LTS.  The date I post the issue is Dec 4 (just wanna say the bug still exists). I have several user experience below:

1. I consider there exists logic bug in the attribute editing module (See the last paragraph).

2. I think the design that "once the user jump into the editing mode by Ctrl+j, all objects' checked boxes are ticked" is awful. I think this can only facilitate the scene that all objects in an image are with the same attribute if they have any, and they could be change at the same time. However, this is not common usage case.

3. It seems the blue row highlight selection is disentangled with the checkbox ticking (they had better be unified into one for user experience since users often think they have already chosen the object they thought however it is not ticked. If I understand correctly only when object is ticked the attribute operation is performing on it right ?).
![image](https://github.com/CVHub520/X-AnyLabeling/assets/8026540/7a6c6e54-2beb-4e30-9dd4-fa62d44854da)

Details about 1: 
     Let me keep describing the bug I met during attribute editing. It is convenient to first annotate several object by bounding box mode. Then I apply Ctrl+j to shift to attribute editing mode. In case of misoperation, I have been trying carefully editing each object attribute at each time by simultaneously blue-highlight it and tick it, and assign it an attribute by selecting in the predefined list (Before assigning attribute of the next object, I untick the previous one, blue-highlight the new object, tick the new object). After finishing assigning attributes to all objects in current frame, I click the '->' arrow to the next image. After that,I turn back by '<-' to examine attributes of the last image. I find that only one object possesses exactly the attribute I have tagged before, leaving the other objects being set to the default attribute (The default attribute is the first in the option list a.k.a. the first in the json file we user specify). I think this behavior might due to some unexpected short-cut attribute inheritance bug that is first designed for certain convenient usage but currently it becomes a bug. Looking forward to your solution.

**Comment by CVHub520** [comment]
Hi, @zhangpzh:

Thank you for bringing this to my attention. The attribute assignment bug you mentioned has been addressed, and the fix is available in the latest source code rather than release version. As many new features are still in development and testing phases, the GUI version has not been released yet. Therefore, please feel free to run the application directly from the source code to access the latest improvements and bug fixes.

Certainly, thank you for your additional comments. Regarding the mentioned functionalities and interactions, I will evaluate them based on practical considerations for future updates. Please stay tuned for further developments.

If you encounter any further issues or have additional feedback, please don't hesitate to let me know.

Best regards,
CVHub
