### ISSUE TITLE
Automate annotation with XAnylabeling tool

### ISSUE THREAD

**Issue by lenka-79** [CVHub520/X-AnyLabeling#149]
Hi,

Right now we have few concerns/issues with Xanylabeling tool
 
1) how to select/use auto run option in this tool
-> while using this option, some frames are skipping b/w the video ( apporx. 30 to 40% farems are skipped) ( tried 2 different models with Grounding dino & Yolo V8 ultralytics )

like multiple frames are skipped in between images

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/30bd52ee-9083-4b9a-8a5e-5f7666ed3586)

2) how to remove /eliminate false detection in frame
-> some times more no of classes are detecting , how to eliminate it, even thought we are using 1 class in my customized class.txt file

3) can we do 100% automation possible using this tool, bcs while using automate some manual intervention is also required to eliminate false detections..

4)  how to reduce flash detection while using automatic annotation option.

5) we are using automate option like below:

![image](https://github.com/CVHub520/X-AnyLabeling/assets/152685134/b1dcefd6-15b7-4f0b-b9a0-1696361cbb56)

6) we are going to use this tool for our on going activities, Need to buy this license or any royalties need to pay for this xanylabeling tool to vendor ?

7) can we eliminate these false detection(multiple bounding boxes are appeared on same pedestrian, few bounding box are not appear it etc..) with licensed tool?

  
Thanks,
L V Giribabu

**Comment by CVHub520** [comment]
Hi, @lenka-79, thank you for your feedback. I will address your concerns one by one:

1. To activate auto-run mode, it needs to be triggered after loading the model. During the process, if the current frame doesn't detect any objects, it will skip and not save an empty file by default.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/a7d0884c-0e12-414e-b360-ff08526419e5)

2. Removing false detections can be done in editing mode, which can be activated by pressing Ctrl+J shortcut. The current mode (Drawing/Editing) will be displayed in the top-left corner.

3. Achieving 100% automation is currently not practical because it contradicts the purpose of data annotation. The tool is designed to assist users in a more convenient and intelligent labeling task with the help of powerful deep learning algorithms, rather than completely replacing human effort.

4. Flash detection depends on the inference time of the model. If you are concerned about this, you can modify the corresponding source code, referencing the [process_next_image](https://github.com/CVHub520/X-AnyLabeling/blob/main/anylabeling/views/labeling/label_widget.py#L3298C9-L3298C27) function.

6. This project follows the [GPL-3.0 license].

7. The ability to eliminate false detections depends on the model settings. The built-in YOLO detection model in X-AnyLabeling allows you to control the generation of overlapping boxes by setting the `--agnostic` parameter or adjusting the `nms_threshold` score. As an entirely open-source tool, its greatest advantage is the rapid support for users' custom requirements. You can customize a model or feature according to your needs.

If you still encounter any further issues or have additional questions, please feel free to ask.

Best regards,
CVHub

**Comment by lenka-79** [comment]
Hi team,

Thanks for ur quick & kind response,
we will check/work on it..

Regards,
L V Giribabu.
