### ISSUE TITLE
No keyboard shortcuts for +Point, -Point etc.

### ISSUE THREAD

**Issue by alexandrewillame** [CVHub520/X-AnyLabeling#153]
Hello,

I noticed there was no keyboard shortcut for for +Point, -Point etc.? Just for "Finish Object" (f). (Using Release v2.1.0)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/7422936/5eb43b90-8a98-47f2-9a0f-3fdde7d54bdb)

Anylabelling have shortcut for all those operations, making this process much faster.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/7422936/931c2729-bf85-438e-802c-8415d93ed55f)

Would be great to add in a future release.

Thank you!

**Comment by CVHub520** [comment]
Hi, @alexandrewillame:

Thank you for your feedback. `X-AnyLabeling` always supports these operations, and in the latest version (just for sources code now), they can be controlled using shortcut Q/E (the same as `AnyLabeling`) for positive/negative keypoint annotations.

In fact, X-AnyLabeling v2.1.0 is quite outdated. The latest source code has incorporated many advanced features and functionalities. I highly recommend running from the source code for a more stable and comprehensive performance. 

Since there are ongoing developments and testing for new features and functionalities, the GUI compiled version may not be released yet. Alternatively, you can compile it based on your specific needs.

Best regards,
CVHub
