### ISSUE TITLE
'YOLOv7' object has no attribute 'task'

### ISSUE THREAD

**Issue by SuhaibAlHindi** [CVHub520/X-AnyLabeling#160]
Other models work normally, but any Yolov7 does not work, even the default one. 
Error Message: 

**Error in predict_shapes: 'YOLOv7' object has no attribute 'task'**

![image](https://github.com/CVHub520/X-AnyLabeling/assets/138457261/282ec32f-5bcc-44b8-8114-3faaa09e6022)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/138457261/3a7d00b1-a1ea-41a8-917a-15beaea230b3)

**Comment by CVHub520** [comment]
Hi, @SuhaibAlHindi:

Thanks for your support of X-AnyLabeling. This issue has been fixed in the [#34d5e9f](34d5e9fa6f32de4b1be24ab776024e9622875140) branch. 

I highly recommend updating to the latest source code to experience more new features and improved stability.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/cd0439ed-0b42-4eac-a88f-27633be841e3)

Best regards,
CVHub
