### ISSUE TITLE
Crash when loading SAM Vit

### ISSUE THREAD

**Issue by alexandrewillame** [CVHub520/X-AnyLabeling#191]
Hello,

I used to use anylabelling  V2.1.0 and everything was fine. Now I just tried V2.2.0 and as soon as I try to use SAM ViT (Large, Base or others), it freeze for a few second to load the model, then everything seem fine, but as soon as I click on "+ Point" to use the segmentation function, it crashes without any more information.

I tried deleting the <user>/appdata/anylabelling folder (that contain the models), it re-download SAM ViT, but still crashes after.

This problem happens on both CPU and GPU version of V2.2.0. Again, this bug was not there on V2.1.0.

It does not happen if loading another model, such as grounding DINO, YoloV8, etc. (please note those models do not have the "+Point" button)

I do not know how to provide more information or if you can reproduce on your end. I would be happy to provide more info if you let me know how.

Thanks!

**Comment by CVHub520** [comment]
Hi, @alexandrewillame:

Thank you for bringing this issue to our attention. Typically, crashing issues like the one you describe tend to affect the GPU version, and we haven't observed such crashes in the CPU version. 

To better diagnose the problem, we suggest that you run the software directly from the source code. This would allow the error message that causes the application crash to be displayed, which will greatly help in identifying the root cause and developing a solution.

If you need guidance on how to run from the source code or capturing the error information, please let us know, and we would be happy to assist you further.

Good luck!
