### ISSUE TITLE
Autolabeling EXIF images with yolo model not correcting input image

### ISSUE THREAD

**Issue by InigTril** [CVHub520/X-AnyLabeling#198]
Hi,

First of all, thank you for this project with very rich and ergonomic functionalities. As a machine learning newbie, I can say it is easy to use!

# Description of the problem
I encountered a problem while trying to autolabel a set of image with EXIF metadata (including a rotation) and a custom Yolov8 model. The inference works, but the bounding boxes are wrongly placed.

# Analysis
I found the origin of the problem: the input image fed to Yolo autolabeling class is the raw image, not the EXIF corrected one, whereas the displayed one correctly takes into account the EXIF, so the predictions are made on an uncorrected image, not rotated and with Red/Blue channels inverted, leading to poor predictions and wrongly placed boxes.
The input image is read at this [line](https://github.com/CVHub520/X-AnyLabeling/blob/903f9a36323c09b08f6e5b06b1ebc32a4be96aa6/anylabeling/services/auto_labeling/__base__/yolo.py#L223). It is called with both the QT image (which has been corrected when it was loaded [here](https://github.com/CVHub520/X-AnyLabeling/blob/903f9a36323c09b08f6e5b06b1ebc32a4be96aa6/anylabeling/views/labeling/label_file.py#L49)) and the image file path. In [this function](https://github.com/CVHub520/X-AnyLabeling/blob/903f9a36323c09b08f6e5b06b1ebc32a4be96aa6/anylabeling/views/labeling/utils/opencv.py#L14C7-L14C7), the file path is preferred, loading the image from the file, but not applying any EXIF correction.

# Proposed solution
EXIF corrections should be applied right after reading the file, just like in the displayed QT image.

# Temporary workaround
In the meantime, I'll just preprocess the EXIF of my images manually to regenerate the dataset.

Have a good day!

**Comment by CVHub520** [comment]
Hi, @InigTril:

Thank you for your kind words about the project and for providing detailed information about the issue you encountered. We appreciate your feedback!

Based on your analysis, it seems like the root cause is the use of the raw image instead of the EXIF-corrected one during autolabeling with Yolov8. Your proposed solution makes sense, and we agree that applying EXIF corrections right after reading the file should address the problem.

We encourage you to contribute to the project by submitting a Pull Request (PR) with your proposed changes. Your contribution will not only help address the issue you faced but also benefit other users who might encounter similar issues. If you have any questions or need assistance with the process, feel free to reach out.

Thank you again for bringing this to our attention, and we look forward to your potential contribution!

Best regards,
CVHub
