### ISSUE TITLE
十分感谢，有没有哪位大哥提供一下MAC OS 的支持啊。

### ISSUE THREAD

**Issue by RFSN** [CVHub520/X-AnyLabeling#254]
希望有为大哥为MAC OS 提供一下支持，Linux 和 windows 都有了。
MAC OS 没有安装包，眼馋的很。
跪谢各位大哥！

**Comment by CVHub520** [comment]
Hello there,

I understand your request for support for MAC OS since Linux and windows are already included. Regrettably, there is no installation package currently available for MAC OS.

In the meantime, you can download the source code and compile it yourself. It's actually quite straightforward. Please refer to the following steps at this [link](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md#%E6%89%93%E5%8C%85%E7%BC%96%E8%AF%91)

Should you encounter further issues, feel free to get in touch with me. 

Best regards.

**Comment by RFSN** [comment]
已经编译成功为mac os 的app 了。但是只能简单的编译CPU版本，使用过程中偶有卡顿，然后master 分支会触发闪退。退回到V2.3.1 版本，基本标注功能可用，希望您后期有条件的时候也能对mac os 提供一些支持，十分感谢。
感谢您的项目。
谢谢。

**Comment by samcaicn** [comment]
[RFSN](https://github.com/RFSN) 能否给个编译后的下载链接哇

**Comment by RFSN** [comment]
不好意思，我也不会编译呢，可以使用python 脚本启动使用，将就用吧，也有个 AnyLabeling 项目，有mac 版本，但是功能貌似没有这个X-AnyLabeling 强大，您可以试试。
