### ISSUE TITLE
Problem exporting to yolo OBB

### ISSUE THREAD

**Issue by fgma** [CVHub520/X-AnyLabeling#377]
I'm running X-AnyLabeling 2.3.5 (also tested 2.3.4) on windows. I'm having problems exporting yolo OBB labels. Steps to reproduce:

1. Annotate some images using rotations tool
2. Create a classes.txt containing all labels used one per line
    - Why do I even need to do this manually?
3. Click on menu upload - upload yolo obb annotations
4. Select classes.txt
5. Select output folder
6. Answer question to allow overwriting existing annotations

- export does not produce any data in the selected directory
- does not matter which folder is as output target
- clicking menu export - yolo annotations results in error list index out of range
- exporting as yolo HBB leads to crash

**Comment by CVHub520** [comment]
Hi, @fgma:

Thank you for your question.

> Why do I even need to do this manually?

This is because the first column of the YOLO label format is a category label, which is usually mapped to a specific number. Therefore, depending on your task, you need to do label mapping.

To correctly export YOLO-OBB labels, please ensure the following:
1. The annotated shape type is the rotation type.
2. The category names defined in the configured category file (classes.txt) correspond to the label names of the annotation boxes.

Lastly, you should select the corresponding export settings from the export menu.

Please be aware of the following:
1. Do not arbitrarily convert different types of annotation shapes.
2. It is recommended to run the source code to immediately view any specific errors.

**Comment by fgma** [comment]
I've tried to export labels according to your description but it still does not work. For testing I created a new dataset based a public image from unsplash. I've double checked annotations contain only rotated shapes.

[debug-dataset.zip](https://github.com/CVHub520/X-AnyLabeling/files/15015279/debug-dataset.zip)

Can you check if this dataset looks good and one can export OBB labels from it?

**Comment by fgma** [comment]
I've found the error but not the cause of the error. It is somehow possible to add labels to an image which are of type rotation but contain only two coordinates. This leads to a crash in the export code because it expects 8 elements.

A nice addon would be to render a marker at the top left corner of rotated annotations.

**Comment by CVHub520** [comment]
Thank you for your valuable feedback! The issue you reported has been addressed and resolved in commit [755c578](https://github.com/CVHub520/X-AnyLabeling/commit/755c578761e7e1b290c1848b26d82f76070ed96a). Your contribution to our project is greatly appreciated.
