### ISSUE TITLE
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

### ISSUE THREAD

**Issue by Augestern-L** [CVHub520/X-AnyLabeling#378]
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by CVHub520** [comment]
Hi, @Augestern-L:

Indeed, your current issue seems to be due to an error in your local environment. A possible solution could be creating a new virtual environment and reinstalling the necessary packages. Here are the steps:

1. Create a new virtual environment: `conda create -n new_env python=3.8 -y`
2. Activate the virtual environment: `conda activate new_env`
3. Install the packages again: `pip install -r requirements.txt`

Please replace 'new_env' with the name you wish to give your new environment and 'requirements.txt' with your actual requirements file if different.

I hope this works for you. If you face any other issues, feel free to ask.

Best Regards.
CVHub
