### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by 5fener** [CVHub520/X-AnyLabeling#407]
在我使用时自动闪退，再也打不开，并且出现以下报错，然后发现无法卸载

![SOIX5K00A}R O7`7AE3`OE8](https://github.com/CVHub520/X-AnyLabeling/assets/80034392/e6f6aea8-58b5-4528-8c20-3bb43649e294)

**Comment by 5fener** [comment]
我重装成功了，无法卸载应该是windows的问题，但是依然打不开

**Comment by CVHub520** [comment]
您好，可以删除用户目录下的 .anylabelingrc 文件后再重启。

**Comment by pythonzz0622** [comment]
They changed the config file name from .anylabelingrc to .xanylabelingrc.

**Comment by dat-nguyenvn** [comment]
more detail please. Where is anylabelingrc and .xanylabelingrc?

**Comment by CVHub520** [comment]
Under your user directory.
















At 2025-04-03 02:56:14, "dat-nguyenvn" ***@***.***> wrote:

more detail please. Where is anylabelingrc and .xanylabelingrc?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

dat-nguyenvn left a comment (CVHub520/X-AnyLabeling#407)

more detail please. Where is anylabelingrc and .xanylabelingrc?
