### ISSUE TITLE
BUG : The software interface disappears

### ISSUE THREAD

**Issue by chenller** [CVHub520/X-AnyLabeling#423]
## Bug description
When I use an AI model for one or more data annotations. Then press the ESC key, and the software interface will disappear. (I'm not sure if this problem will occur 100%, but I've encountered it many times.)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/62296334/0aad0561-d8d6-4829-b723-7d63b3b8355b)
**Press the ESC key**
![image](https://github.com/CVHub520/X-AnyLabeling/assets/62296334/62018fe4-8363-4d84-9de7-a32834caf322)
## Operating Environment
- Software version : Latest
- Python 3.10.14

**Comment by CVHub520** [comment]
Thank you for bringing this issue to our attention; I’ll check it later.

**Comment by shojint** [comment]
May I ask why this issue won't be fixed? Thank you.

**Comment by CVHub520** [comment]
Hey there! @chenller @shojint 

Thank you for reporting this bug. I've investigated the issue where the interface disappears when pressing the ESC key during AI model annotations, and I'm happy to inform you that it has been fixed.

The problem was related to how keyboard events were being handled - specifically the ESC key press event. I've implemented a fix that properly intercepts the ESC key event and prevents it from causing the interface to disappear while maintaining all other keyboard functionality.

The fix has been committed to the main branch and will be available in the next release. If you'd like to apply the patch immediately, you can update to the latest commit.

Please let me know if you encounter any further issues with the ESC key or any other keyboard shortcuts.

#228
