### ISSUE TITLE
不管是CPU还是GPU加载自定义模型都闪退

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#469]
你好 用的是这个2版本
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/5ca64bfb-6dcf-4645-a7e7-c6d8065360b8)
   加载自定模型的时候 一直在闪退
   只要在这里加载了自定义模型 就肯定闪退
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/ac2b6888-c698-4d5d-861a-180b0ecfbcc7)

   是我的 模型文件写错了吗？
   
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/c3fbf6d1-5491-41f3-8dc4-d3954c833bb4)
不能直接点加载这个文件么
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/8b0f72ad-443c-4860-ace5-53bbebb7e2f1)

**Comment by CVHub520** [comment]
@lhj5426, Hey there! 🤓 

Thanks for you bring this to our attention. It seems that the issue with the application crashing when loading a custom model, whether on CPU or GPU, might be due to an incorrectly formatted YAML configuration file. 

In YAML, it's important to have a space between the key and the value. Please check your configuration file and ensure that it follows the correct format:
```yaml
# Invalid format (no space between key and value):
model:xxx
# Valid format (space between key and value):
model: xxx
```
Make sure to correct the formatting in your YAML file, and the crashing issue should be resolved. If you continue to experience problems, please provide more details or the specific section of your YAML file for further assistance.

**Comment by lhj5426** [comment]
感谢您的帮助安装你的 指点
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/1f75ddac-9edc-4dbe-8707-19f035f67b32)
可以正确载入 并运行 模型进行检测了 非常感谢您的帮助
