### ISSUE TITLE
`Qt_5.15' not found

### ISSUE THREAD

**Issue by littlepiper** [CVHub520/X-AnyLabeling#475]
I followed the instruction manual and installed the relevant dependencies, but I encountered an error when starting the program. The error message is:
、、、
File "anylabeling/app.py", line 19, in <module>
    from PyQt5 import QtCore, QtWidgets
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found
、、、
How can I solve this problem? Do I need to install Qt 5.15 on my Linux system environment? It seems the system environment only has 5.12. Or is there any other solution? This error has been bothering me for several days.

**Comment by CVHub520** [comment]
Hi, @littlepiper,

I noticed that you’ve encountered an issue with the PyQt5 version on your Linux system and have since closed the issue. I’m curious if you’ve found a solution to the problem? If so, could you share how you resolved the “version `Qt_5.15’ not found” error? Did you end up installing Qt 5.15, or did you find an alternative workaround?

Your experience could be helpful for others facing similar issues. Thank you in advance for your time and assistance!

Best regards,
CVHub
