### ISSUE TITLE
Could you add a feature for dragging or merging multiple selected rectangles?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#499]
Dear Developer,

I am using the annotation software you developed to annotate text on comic images. I am using YOLOv8 for training the model, which is still in its early stages. During the training and annotation process, there is a specific workflow. Please watch the video.

https://github.com/CVHub520/X-AnyLabeling/assets/30548000/9f18b209-c2fc-4e85-84f8-28f4aa661da2

Because the model is in its early stages, it can recognize text but often incorrectly. You see, I have a bunch of rectangles here that I need to delete and then draw a new rectangle, and then modify it to the correct label. This process is very cumbersome.

So, I have a favor to ask. Could you please add a "select all and merge rectangles" feature like in video 2?

https://github.com/CVHub520/X-AnyLabeling/assets/30548000/e2313742-5337-4cd1-b0e0-7a53dea8fca8

This way, it would greatly reduce the number of steps. I could directly select all, merge, and modify the labels, without having to delete each one individually by pressing the delete key. Could you consider this request? Thank you.

**Comment by CVHub520** [comment]
Got it! 💯

**Comment by CVHub520** [comment]
Hey there! @lhj5426😊,

I'm super excited to announce that the feature you've been asking for 🙌 - the ability to merge multiple rectangle shapes into a single shape representing their union - has now been implemented and pushed to the GitHub repository 🎉.

To try out this new feature, here's what you need to do:

1. Pull the latest source code from the repository to ensure you have the updated version 🔄.
2. Select the rectangle shapes you want to merge by holding down the Ctrl key while clicking on them with your mouse 🖱️.
3. Once you have multiple shapes selected, hold down Ctrl and right-click on the canvas. You will see a context menu where you can choose the "Union Selection" option 📏.

After selecting "Union Selection," the tool will create a new shape that represents the union of the selected rectangles. Please let me know if you encounter any issues or have further questions about this feature 🤝.

Happy labeling! 😃


https://github.com/CVHub520/X-AnyLabeling/assets/72010077/7e15bd04-bdba-4533-87b5-98d44121255a

**Comment by lhj5426** [comment]
> Hey there! @lhj5426* 😊,
> 
> I'm super excited to announce that the feature you've been asking for 🙌 - the ability to merge multiple rectangle shapes into a single shape representing their union - has now been implemented and pushed to the GitHub repository 🎉.
> 
> To try out this new feature, here's what you need to do:
> 
> 1. Pull the latest _source_ code from the repository to ensure you have the updated version 🔄.
> 2. Select the rectangle shapes you want to merge by holding down the Ctrl key while clicking on them with your mouse 🖱️.
> 3. Once you have multiple shapes selected, hold down Ctrl and right-click on the canvas. You will see a context menu where you can choose the "Union Selection" option 📏.
> 
> After selecting "Union Selection," the tool will create a new shape that represents the union of the selected rectangles. Please let me know if you encounter any issues or have further questions about this feature 🤝.
> 
> Happy labeling! 😃
> 
>  23-26-42._mp4_

I really appreciate your response, developers.
Thank you so much.
And then I have two questions. Could you take a look at them?


https://github.com/CVHub520/X-AnyLabeling/assets/30548000/fa5ae73f-485e-49db-a8f0-9033f525b589


Sometimes, the trained model recognizes a situation where a large rectangle contains many smaller rectangles.
In such cases, it is impossible to select the smaller rectangles under the large rectangle.
As a result, it is not possible to use Ctrl to select and merge them.
This is one issue.
Is this possible to solve?
Another issue is, could you please add a shortcut key for merging rectangles?

![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/ae0dd514-e84b-4e00-80c0-e7a135464dd3)

When I am labeling, I use a small keypad that allows for custom button functions.
If you could add a shortcut key, users could conveniently use the shortcut to quickly merge rectangles,
instead of having to right-click the menu and click to merge each time.
Could you please consider adding a shortcut key?
![image](https://github.com/CVHub520/X-AnyLabeling/assets/30548000/cfec51cd-93ab-4758-8efc-b2bfd81083f0)

Any shortcut key would be fine, as I am using a keypad that can customize functions.


Thank you very, very much!

**Comment by lhj5426** [comment]
Also, although clicking is convenient, sometimes when there are many rectangles that I want to merge, I have to hold down Ctrl and then precisely click each rectangle. This operation is not very user-friendly. If it were possible to hold down Ctrl and drag to select multiple rectangles, and then release Ctrl while still being able to use the merge option in the menu, it would be much more user-friendly. Holding down Ctrl all the time makes it easy to forget that you need to hold down Ctrl and then right-click to activate the function. Could you please optimize this operation logic? Sorry for the trouble.

**Comment by lhj5426** [comment]
After selecting, I habitually release the Ctrl key because, in Windows, you typically release Ctrl after making a selection. Out of habit, I subconsciously release it. Then I realize that the merge option in the right-click menu is not activated, so I have to go back, hold down Ctrl again, click the rectangles, and this time remember not to release Ctrl before using the right-click menu. But then I forget again the next time. I repeated this process many times in one evening. This interaction is really not very user-friendly.

**Comment by lhj5426** [comment]
Or, by holding down the Alt key, you can draw a rectangle to select multiple rectangles that fall within the drawn area, and then merge them directly when you release the left mouse button.

**Comment by lhj5426** [comment]
Ctrl + left-click is for single selection, and Alt + drag to draw a rectangle is for batch selection and merging. Both of these interaction logics feel quite user-friendly.

**Comment by CVHub520** [comment]
Hi, there! 👋 

Thank you for your detailed feedback and constructive suggestions. Here are the responses to the issues you raised:

1. Occlusion issue: Indeed, selecting shapes when larger shapes overlap smaller ones can be cumbersome. Currently, you can use the shortcut key 's' to temporarily hide the topmost shape to access the ones underneath. We will further evaluate this issue and consider optimizations in future versions to more conveniently handle occlusions.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/b770c27d-f571-44f2-9f61-57bd7cbf4803)

3. Shortcut key for merging rectangles: Your suggestion to add a shortcut key for merging rectangles is very practical. We will take this into consideration for future updates, allowing users to customize shortcut keys according to their preferences and device capabilities, thereby enhancing the labeling efficiency.

4. Selection and merging operation optimization: Your insights on the operation logic for selecting multiple rectangles and merging them are highly valuable. We will explore ways to optimize the use of the merge option in the right-click menu while maintaining the Ctrl key selection, in order to reduce the number of steps and cognitive load for users. Additionally, we will consider incorporating a feature similar to the one you suggested, where holding down the Alt key allows you to drag and select multiple rectangles for direct merging, providing a more user-friendly experience.

We highly appreciate your feedback as it helps us continuously improve our product and service. Thank you for your understanding and patience. I will strive to address these issues in future updates and continue optimizing X-AnyLabeling. If you have any further suggestions or questions, please feel free to contact me.
