### ISSUE TITLE
图像垂直翻转的问题

### ISSUE THREAD

**Issue by dahaigui** [CVHub520/X-AnyLabeling#513]
我使用Pillow将图像进行垂直翻转之后，使用图像查看器查看，图像已经翻转，但是在X-AnyLabeling软件中并没有翻转，这是为什么？

**Comment by CVHub520** [comment]
Hey there! @dahaigui,

Thank you for reaching out and bringing this discrepancy to our attention. I have tested the function using Pillow to vertically flip images, and it appears to be functioning correctly on my end. When I view the flipped image using standard image viewers, the image is indeed flipped vertically as expected.

```python
from PIL import Image

def flip_image_vertical(input_path, output_path):
    with Image.open(input_path) as img:
        flipped_img = img.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
        flipped_img.save(output_path)

input_image_path = 'path/to/your/input/image.jpg'
output_image_path = 'path/to/your/output/image_flipped.jpg'

flip_image_vertical(input_image_path, output_image_path)
```

The issue you're experiencing seems to be specific to X-AnyLabeling software. This could be due to various reasons such as differences in how the software interprets image metadata or a potential bug within the software itself when handling flipped images.

To ensure that we're aligned with the latest updates and improvements, I recommend updating your codebase to use the latest version of X-AnyLabeling. This will allow us to benefit from any bug fixes and optimizations that may have been included in newer releases.

Please let me know if you require any further assistance or if there's anything else I can help you with.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/325377d3-b063-4fc7-9471-b26c9d362aa2)


![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/ba6c2ad1-3c2c-435f-a18c-f08f2fedf2ca)

**Comment by dahaigui** [comment]
My code is as follows
```
def vertical_flip_image(image_path, output_path):
    image = Image.open(image_path)

    flipped_image = image.transpose(Image.FLIP_TOP_BOTTOM)

    flipped_image.save(output_path)
```
This doesn't seem to be much different from your code, but my image is not flipped in X-AnyLabeling, although when I view the image using the Image Tool, it is flipped.
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/cae8ffb5-2440-4d15-90b6-9a5b759e20a6)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/b3f3e1a4-0947-412f-9e3c-42c1e032727f)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/ba0ea94d-20e9-4b07-91d6-821ee7f045da)
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/6f1b79e5-64ee-4e4c-9287-6190bbd84ea2)

**Comment by dahaigui** [comment]
I'm using version 2.3.6, and I still have this problem. Could you please let me send you the picture via email?

**Comment by CVHub520** [comment]
> I'm using version 2.3.6, and I still have this problem. Could you please let me send you the picture via email?

Yes. Please zip the images and send to the email: cv_hub@163.com

**Comment by dahaigui** [comment]
> > I'm using version 2.3.6, and I still have this problem. Could you please let me send you the picture via email?
> 
> Yes. Please zip the images and send to the email: [cv_hub@163.com](mailto:cv_hub@163.com)

I just sent it to this email

**Comment by CVHub520** [comment]
Does this meet your expectations?

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/edecc2f9-e2f4-44b8-a20d-3be74321d39a)

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/61ac29c2-0a3a-4629-b73b-513305700693)

**Comment by dahaigui** [comment]
Yes！Exactly！

**Comment by CVHub520** [comment]
As I mentioned above, please pull the latest source code and run it, do not use the GUI version.

**Comment by dahaigui** [comment]
I am using the version 2.3.6, I'll try the 2.3.7 version of the source code right away.

**Comment by dahaigui** [comment]
I'm using the latest version of the source code, but this problem still occurs.
![image](https://github.com/CVHub520/X-AnyLabeling/assets/47802187/65aef480-7e56-44c6-b50a-5f3c09f17e15)

**Comment by CVHub520** [comment]
This is not the latest version of the source code, but a release version that was published a few months ago. Please use the git clone method to pull the latest source code, or download it directly from here.

![image](https://github.com/CVHub520/X-AnyLabeling/assets/72010077/71aabb04-0786-4699-afa0-4e8759ec67c4)


> Release版本：
> 通常指的是项目维护者发布的稳定版本，这些版本在发布前经过了测试，旨在提供给用户一个稳定可靠的软件版本。
> Release版本并不会包含最新的开发进展或最近的修复，因为它们是定期发布的。
> 用户可以通过项目页面上的 release 下载链接直接获取Release版本。
> 
> Git版本：
> Git 是从项目的源代码仓库中克隆最新的开发版本。这个版本通常包含了最新的功能、修复和改进。
> 克隆的版本可能是开发中的，可能不如Release版本稳定，但它们提供了最新代码的访问。

**Comment by dahaigui** [comment]
I met the same problem, maybe my dependencies are not updated. I will try to reinstall the environment.

**Comment by dahaigui** [comment]
I updated my dependencies and still have this problem. Will this problem affect my use of this data to train the yolov8s-seg model?

**Comment by CVHub520** [comment]
The statement doesn't seem coherent, as the image loading process is not related to the system's env.

Incidentally, data augmentation is not advisable to be performed offline. Instead, it should be incorporated as a preprocessing step within the training framework. Therefore, I recommend annotating the original file without augmented images, such as flips, rotations, and other transformations.

**Comment by dahaigui** [comment]
OK, thank you very much for your suggestion. I just changed a computer and tried it, and the display is normal. This problem may be caused by some bugs in my computer.

**Comment by CVHub520** [comment]
Thank you for your feedback! 

I'm glad to hear that switching to a different computer resolved the display issue. It's possible that the problem was indeed related to specific bugs on your previous machine. Your update is helpful for us to understand the context and potential causes.

 If you encounter any more issues or have further suggestions, please don't hesitate to let us know. Your input is valuable to us!

**Comment by dahaigui** [comment]
I just discovered that when I packaged the pictures directly into a compressed package, which is the picture I sent to you yesterday, there was no such problem. However, when I packaged the picture folder I generated and then decompressed it on the computer I used this morning, the problem still existed. I will send you the picture folder again to see what the reason is.

**Comment by dahaigui** [comment]
I found the problem, it might be caused by my json file. After I deleted the json file, I can view it normally.

**Comment by dahaigui** [comment]
I have found the problem now, that is, the imagePath in my json file has not been modified
