### ISSUE TITLE
将图片A的矩形框（labels）全部删除……未自动保存！！！

### ISSUE THREAD

**Issue by 93yh** [CVHub520/X-AnyLabeling#518]
将图片A的矩形框（labels）全部删除（勾选了自动保存标注），按D键，标注下一张图片B，继续标注，结果按A键，返回之前那个图片A，出现图片B标注的矩形框，按道理，图片A应该没有任何矩形框！！！

**Comment by CVHub520** [comment]
@93yh, Hey there! 👏

Thank you for bringing this to our attention. When you enable the 'Auto-save` annotation feature, it is designed to copy the annotations from the previous image to the next one you switch to. This behavior is particularly useful for annotating consecutive frames or redundant frames where the annotations are similar.

However, if you need to ensure that each image's annotations are unique and you want to check the annotations on previously annotated images, it's important to disable this option. In your case, the issue you're experiencing with the annotations from image B appearing on image A after returning to it is due to the 'Auto-save Annotation' feature being active.

To avoid this, please make sure to turn off the option before you start annotating. This will prevent the annotations from being carried over to other images inadvertently. Thank you for your understanding, and i hope this resolves the confusion. 😊

**Comment by 93yh** [comment]
谢谢您
