### ISSUE TITLE
Why not include sam_vit_hand hq_sam_huge

### ISSUE THREAD

**Issue by yummy527** [CVHub520/X-AnyLabeling#527]
Thanks for your great work!

Some people like me want to use largest SAM models (sam_vit_h and hq_sam_huge, unquantized ones) . Why don't you provide them?

They are too large to upload to github? I am not sure.

I tried to convert format `sam_vit_h` model to `.onnx`, getting two files for encoder: `sam_vit_h_4b8939.encoder_data.bin` and `sam_vit_h_4b8939.encoder.onnx`. I am not sure if it is correct, because only one encoder file for other models.

**Comment by CVHub520** [comment]
Hey there!
@yummy527 Thank you for your kind words and for your interest in using the largest SAM models!
Regarding the inclusion of sam_vit_huge and hq_sam_huge in our repository, there are a few considerations to take into account:
1. Repository Size Constraints: As you mentioned, these models are quite large, which is makes it challenging to download for user.
2. Focus on Baseline Models: Our primary goal is to provide a template or baseline for users to utilize X-AnyLabeling. There are numerous models available, and it's not feasible for us to support all of them directly. However, we aim to offer a starting point that users can build upon.
Here are some suggestions for you:
- Model Conversion: If you are unsure about the correctness of the conversion, you might want to validate the model by running inference on a sample dataset and comparing the results with the original model's output.
- Model Deployment: You can use the converted model within the X-AnyLabeling tool. Since we cannot handle all models directly, we encourage users like you to convert and deploy the desired models themselves. You can refer to our documentation or reach out to the community for assistance with integrating custom models.
- Community Support: Consider sharing your converted model and the steps you took with the community. This can be beneficial for others who are looking to use the same or similar models with X-AnyLabeling.
We appreciate your understanding and are here to support you in any way we can as you work with these models. 

If you encounter any issues or have further questions, please feel free to reach out!

**Comment by yummy527** [comment]
> Hey there! @yummy527 Thank you for your kind words and for your interest in using the largest SAM models! Regarding the inclusion of sam_vit_huge and hq_sam_huge in our repository, there are a few considerations to take into account:
> 
>     1. Repository Size Constraints: As you mentioned, these models are quite large, which is makes it challenging to download for user.
> 
>     2. Focus on Baseline Models: Our primary goal is to provide a template or baseline for users to utilize X-AnyLabeling. There are numerous models available, and it's not feasible for us to support all of them directly. However, we aim to offer a starting point that users can build upon.
>        Here are some suggestions for you:
> 
> 
>     * Model Conversion: If you are unsure about the correctness of the conversion, you might want to validate the model by running inference on a sample dataset and comparing the results with the original model's output.
> 
>     * Model Deployment: You can use the converted model within the X-AnyLabeling tool. Since we cannot handle all models directly, we encourage users like you to convert and deploy the desired models themselves. You can refer to our documentation or reach out to the community for assistance with integrating custom models.
> 
>     * Community Support: Consider sharing your converted model and the steps you took with the community. This can be beneficial for others who are looking to use the same or similar models with X-AnyLabeling.
>       We appreciate your understanding and are here to support you in any way we can as you work with these models.
> 
> 
> If you encounter any issues or have further questions, please feel free to reach out!

Thanks for your reply.

I converted SAM-huge model with [samexporter](https://github.com/vietanhdev/samexporter.git), which is easy to use. And constructed a customized model config following your [custom-model instruction](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/en/custom_model.md) with success.

After trying the base, large and huge model (not quantized) of SAM model, I found that segmentation results of all these models were not as good as the [SAM demo](https://segment-anything.com/demo). Specifically speaking, the segmentation boundary did not match the object edge even though some control points were added. In contrast, dedicated segmentation of the same object could be achieved by just one click. 

I am wondering what lead to the difference between the SAM demo and the local SAM-huge. Hardware (GPU) performance or model parameters?

**Comment by CVHub520** [comment]
Hello there,

Thank you for the update and for sharing your experience with the SAM model conversion and usage. I'm glad to hear that the `samexporter` tool was user-friendly and that you successfully constructed a custom model config! 

Regarding the difference in segmentation quality between the SAM demo and your local SAM-huge model, there are a few potential factors to consider:

1. **Model Conversion Precision**: As mentioned in the reference materials, when converting the `.pth` model to `.onnx`, there can be some precision loss. This is a common issue when moving models between different frameworks or runtime environments.
2. **Preprocessing and Postprocessing**: Inconsistencies in preprocessing (like image normalization) and postprocessing steps can also lead to differences in the output quality.

To address these issues and potentially improve the segmentation results:

- **Integrate SAM-pth**: If you're looking to achieve the most accurate results, integrating the SAM-pth model directly into X-AnyLabeling, as suggested, could be the best approach. This would require you to have the appropriate PyTorch packages installed.
- **Check Preprocessing/Postprocessing**: Ensure that the preprocessing and postprocessing steps in your local setup match those used in the SAM demo.

If you decide to integrate the SAM-pth model, please follow the documentation carefully and let us know if you encounter any issues during the integration process. We're here to help! 🚀

Looking forward to your progress and hope this helps you achieve the desired segmentation results.

Best regards,
CVHub Maintainer
