### ISSUE TITLE
ValueError: Required inputs (['input_image']) are missing from input feed (['image_embeddings', 'point_coords', 'point_labels', 'mask_input', 'has_mask_input', 'orig_im_size']).无法自动标注，报错

### ISSUE THREAD

**Issue by cakuYu** [CVHub520/X-AnyLabeling#530]

**Comment by CVHub520** [comment]
Hi, it appears that the error you're encountering, `ValueError: Required inputs (['input_image']) are missing from input feed...`, is due to a mismatch between the exported ONNX model and the model expected by the X-AnyLabeling tool. The inputs expected by the tool are not present in the model you've provided.

To resolve this issue, you can try one of the following two solutions:

1. Follow the instructions in the [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/custom_model.md#%E4%B8%89%E5%A6%82%E4%BD%95%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B) to export your model correctly. After exporting, use the [netron](https://netron.app/) tool to inspect the input and output nodes of your ONNX model to ensure they match the expected inputs of X-AnyLabeling.
2. If the first solution doesn't work for you, you can modify the [model inference script](https://github.com/CVHub520/X-AnyLabeling/tree/main/anylabeling/services/auto_labeling) to accommodate your custom model. This will involve updating the script to handle the specific input and output nodes of your ONNX model.

Please try these solutions and let us know if you encounter any further issues. If you need more detailed assistance, feel free to ask!
