### ISSUE TITLE
Error in loading custom model: Invalid config file format.

### ISSUE THREAD

**Issue by Thompson21666** [CVHub520/X-AnyLabeling#533]
导入自己的模型时显示Error in loading custom model: Invalid config file format.需要如何解决呢？
![微信图片_20240718204728](https://github.com/user-attachments/assets/d3142b38-50a4-415e-b268-b9d6663e438e)
![微信图片_20240718204737](https://github.com/user-attachments/assets/cda44d42-db17-47ef-9799-7af5bd0c8772)

**Comment by CVHub520** [comment]
Hi @Thompson21666,

It appears that you're encountering an issue with loading your custom model due to an 'Invalid config file format' error. To resolve this, you might need to check the configuration file for any syntax errors or missing required fields.

Since you are using the AnyLabeling tool rather than `X-AnyLabeling`, it would be best to seek help from the developers or the community associated with that project. You can do this by moving your question to the [AnyLabeling repository](https://github.com/vietanhdev/anylabeling). Please open an issue there or search through the existing issues to see if someone else has encountered a similar problem and found a solution.

When you do, make sure to include details about your config file and any other relevant information that could help diagnose the issue. The developers and the community will be able to provide more targeted assistance. 

Good luck!
