### ISSUE TITLE
How to Add Flags While Labeling in the Apps for Image-level and Shape-level Classification

### ISSUE THREAD

**Issue by ChenPingChen** [CVHub520/X-AnyLabeling#539]
請問怎麼在apps內，標註的同時加入flags？
例如，標註「安全帽helmet」，可分別註明是白色、紅色、藍色等等....

**Comment by CVHub520** [comment]
Hey there~ @ChenPingChen,

My apologies once again for the oversight. In addition to the previous information, if you are working with image-level classification annotations, you can directly launch the app using the following command:

```bash
python anylabeling/app.py --labels helmet --flags red,white,blue
```
This command will start the annotation process for the "helmet" label with the flags "red," "white," and "blue" for classification purposes. It allows you to easily specify the labels and associated flags directly from the command line. 

![image](https://github.com/user-attachments/assets/6a7125e7-e178-4820-ae41-0b513a5ddce6)

Otherwise, if you are working shape-level classification annotations, you can just follow this [toturial](https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/user_guide.md#%E5%A4%9A%E6%A0%87%E7%AD%BE%E5%88%86%E7%B1%BB%E4%BB%BB%E5%8A%A1%E6%A0%87%E6%B3%A8).

Additionally, here is an example file that you can use as a reference:

```json
{
    "helmet": {
        "color": [
            "blue",
            "red",
            "white",
            "yellow"
        ]
    }
}
```

https://github.com/user-attachments/assets/09d6f820-2355-44d8-b749-3c7ee0a0da7a

This example shows how to annotate “helmet” with different colors such as red, white, blue and yellow. 

Further to the information provided, I would like to add that the current shape-level attribute annotation feature is not yet fully refined and may not be as user-friendly as we aim for. We are aware of this and are committed to continuous improvement. Please stay tuned for future updates that will enhance the user experience. 

Should you encounter any issues or require more detailed guidance, please don't hesitate let me know. Thank you for your understanding and kindly patience. 😄

**Comment by ChenPingChen** [comment]
Thanks for your comment.
