### ISSUE TITLE
The imported video was split into images?

### ISSUE THREAD

**Issue by lhj5426** [CVHub520/X-AnyLabeling#562]
Hello respected developer,
After training my model, I wanted to try running the model's detection results on a comic-style video. However, when I imported the video into the software, I found that the software split it into individual frames instead of importing the entire video. Is this normal, or did I miss setting something?
![image](https://github.com/user-attachments/assets/4a11b3d7-f141-4bcf-bcaf-d48fc350e372)

![image](https://github.com/user-attachments/assets/6393ca2b-3a91-4375-9815-6286ceb4b786)

![image](https://github.com/user-attachments/assets/146946b2-4ef9-4f34-8447-2313fef99af0)

**Comment by CVHub520** [comment]
Hello @lhj5426 👋,

Thank you for reaching out and for your kind words!

What you're experiencing is indeed the expected behavior of the software. When you import a video into X-AnyLabeling, it is automatically parsed into individual frames based on the frame extraction frequency that you've set. This allows for frame-by-frame analysis and labeling, which is particularly useful for detailed model training and testing.

If you intended to work with the video as a continuous stream, this feature might seem unexpected. However, for comic-style videos or any video content, this frame-by-frame approach is often necessary to capture the nuances and details needed for accurate detection results.

If you're looking to adjust the frame extraction settings, you can do so in the software's preferences. Alternatively, if you need assistance with this, please refer to our documentation or let me know, and I'd be happy to guide you through the process.

希望这能帮助到你！📚 If you have any more questions or need further clarification, please don't hesitate to ask.

Best regards,
X-AnyLabeling Maintainer

**Comment by lhj5426** [comment]
I see, but when I directly used YOLO's inference command, it generated an AVI format video that displayed the inference results in real-time. Therefore, I was puzzled when I noticed that your software shows the results as images. Thank you for your explanation.

**Comment by CVHub520** [comment]
Hello, thank you for your inquiry. 🌵 

Indeed, as you mentioned, saving image frames as a video is a straightforward process. X-AnyLabeling currently displays the inference results as individual images for each frame, which allows users to inspect the details of each frame more closely. 

However, if you wish to combine these image frames into a video, you can easily do so after the inference is complete by using video processing tools like FFmpeg. This will allow you to create an AVI or any other format video with the real-time inference results. 

I hope this explanation is helpful to you. 😄
