### ISSUE TITLE
Error in loading model : [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from

### ISSUE THREAD

**Issue by AImagicAI** [CVHub520/X-AnyLabeling#574]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

Hello, when I am using the software to load the model SAM-Med2d, the error message is as follows:

Error in loading model : [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from    .....onnx failed: Protobuf parsing failed

May I ask what the reason is?

**Comment by CVHub520** [comment]
Hello @AImagicAI, 👋

Thank you for reaching out and for using X-AnyLabeling. I'm sorry to hear that you're encountering an issue with loading the SAM-Med2d model.

The error message you're seeing, `[ONNXRuntimeError] : 7 : INVALID_PROTOBUF`, typically indicates that there's a problem with the Protobuf file, which could be due to the file being incomplete or corrupted.

🔍 From the reference materials provided, it's likely that the ONNX file did not download completely. Here are a few steps you can take to resolve this issue:
1. **Redownload the Model**: Try deleting the existing `.onnx` file and downloading it again from the original source to ensure you have a complete and uncorrupted file.
2. **Check File Integrity**: After downloading, you can verify the integrity of the file by checking its size against the expected size or by using checksums if they are provided.
3. **Ensure Proper Permissions**: Make sure that the file has the correct permissions to be read by the software.

If these steps do not resolve the issue, please let us know, and we can investigate further. Also, if you have any additional details about the environment in which you're running the software (such as operating system, ONNXRuntime version, etc.), that could be helpful in diagnosing the problem.

Looking forward to helping you get past this hurdle! 🚀

![image](https://github.com/user-attachments/assets/35795e4f-5642-4c3f-9d3d-ac047118d1f6)
