### ISSUE TITLE
采用sam2模型 重置跟踪器时提示An error occurred while resetting the tracker: 'point_inputs_per_obj' 一次运行所有图片时没结果

### ISSUE THREAD

**Issue by qfxb** [CVHub520/X-AnyLabeling#614]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Model

### Bug

重置跟踪器时提示An error occurred while resetting the tracker: 'point_inputs_per_obj'

### Information

{'App name': 'X-AnyLabeling', 'App version': '2.4.1', 'Device': 'CPU'}

System Information:
{ 'CPU': 'Intel64 Family 6 Model 151 Stepping 2, GenuineIntel',
  'CUDA': 'V11.7.99',
  'GPU': '0, NVIDIA GeForce GTX 1650, 4096',
  'Operating System': 'Windows-10-10.0.22631-SP0',
  'Python Version': '3.10.14'}

Package Information:
{ 'ONNX Runtime GPU Version': None,
  'ONNX Runtime Version': None,
  'ONNX Version': '1.16.2',
  'OpenCV Contrib Python Headless Version': None,
  'PyQt5 Version': '5.15.11'}

### Link to a Reproducible Demonstration Video

https://easylink.cc/eib5fb

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
This behavior is not indicative of a bug. :(

When you reset the tracker, it's essential to clear all previously annotated shapes on first frame and re-add the desired prompts before initiating the tracking process. In the video you provided, it appears that you clicked the `run_all` button directly without performing these necessary steps. As a result, the tracker did not receive any prompts to process, which is why it produced no output.

Regarding the error message “An error occurred while resetting the tracker: ‘point_inputs_per_obj’,” this is triggered when no prompts have been added before attempting to reset the tracker. It’s important to note that upon initial model loading, there is no need to reset the tracker. However, if this step is taken, it’s not detrimental; it simply has no effect on the functionality.

To effectively use this feature, please adhere strictly to the guidelines provided in our [tutorial](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/interactive_video_object_segmentation/README.md). Additionally, you may find our [demo video](https://www.bilibili.com/video/BV1kMpwedE8M) helpful for a visual reference on the correct usage of the tool. Following these steps should ensure a successful tracking experience.

**Comment by qfxb** [comment]
很抱歉我没有正确操作，但是请看我下面的视频，我完全按照教程执行代码也是无法对后续帧进行标注的而且代码中还会报错
https://easylink.cc/w3pc2c

**Comment by CVHub520** [comment]
> 很抱歉我没有正确操作，但是请看我下面的视频，我完全按照教程执行代码也是无法对后续帧进行标注的而且代码中还会报错 https://easylink.cc/w3pc2c

I apologize for the inconvenience you've encountered. However, after reviewing the video you provided, it is evident that the error `ImportError: cannot import name '_C' from 'sam2'` is due to an incomplete or incorrect installation of the required environment.

Please follow the instructions provided in the installation guide at [INSTALL.md](https://github.com/CVHub520/segment-anything-2/blob/main/INSTALL.md) to ensure that your environment is set up correctly before running the program. It is crucial to have all the necessary dependencies installed to avoid such issues.

In the future, please make sure that all the required environments are properly installed before proceeding with the operations. This will save time for both us. :( Thank you for your understanding and cooperation.
