### ISSUE TITLE
label name sort not in order

### ISSUE THREAD

**Issue by Twenty3hree** [CVHub520/X-AnyLabeling#627]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

things not go well, when object 0, 1, 2, 3, ..., 10, 11, ..., 21

order will be 0, 1, 10, 11...

hope fix~ good work!

![1726136977463](https://github.com/user-attachments/assets/f0d949ec-12b2-450d-9816-ed2ca648ff2a)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
👋 Hi @Twenty3hree! Thank you for bringing this to our attention and for your suggestion. 🙌

I've implemented natural sorting for the QListWidget labels, which should address the issue you've pointed out. The labels will now be sorted as 0, 1, 2, ..., 10, 11, ... instead of 0, 1, 10, 11, 2, 3, ...

This change has been committed to the repository. 🎉

Could you please update to the latest version and verify if this solves your problem? If you encounter any issues or have any further suggestions, please don't hesitate to let us know. 

Your feedback is invaluable in helping me improve X-AnyLabeling. Thank you for your contribution to the project! 🚀

**Comment by CVHub520** [comment]
👋 Hi @Twenty3hree! Thank you for bringing this to our attention and for your suggestion. 🙌

I've implemented natural sorting for the QListWidget labels, which should address the issue you've pointed out. The labels will now be sorted as 0, 1, 2, ..., 10, 11, ... instead of 0, 1, 10, 11, 2, 3, ...

This change has been committed to the repository. 🎉

Could you please update to the latest version and verify if this solves your problem? If you encounter any issues or have any further suggestions, please don't hesitate to let me know. 

Your feedback is invaluable in helping us improve X-AnyLabeling. Thank you for your contribution to the project! 🚀
