### ISSUE TITLE
Assertion error during canvas painting

### ISSUE THREAD

**Issue by hoeoek** [CVHub520/X-AnyLabeling#630]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Tool, User Interface (UI)

### Bug

I was labelling rectangular bounding boxes and I might have pressed something else that "r" (for new rect), but I was in a trance so I wasn't super attentative.

```
Traceback (most recent call last):
  File "/Users/cnok0001/LOCAL/X-AnyLabeling/anylabeling/views/labeling/widgets/canvas.py", line 1181, in paintEvent
    shape.paint(p)
  File "/Users/cnok0001/LOCAL/X-AnyLabeling/anylabeling/views/labeling/shape.py", line 248, in paint
    assert len(self.points) in [1, 2, 4]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
[1]    90817 abort      python3 anylabeling/app.py
```

### Information

Application Information:
{'App name': 'X-AnyLabeling', 'App version': '2.4.2', 'Device': 'CPU'}

System Information:
{ 'CPU': 'i386',
  'CUDA': None,
  'GPU': None,
  'Operating System': 'macOS-15.0-x86_64-i386-64bit',
  'Python Version': '3.12.3'}

Package Information:
{ 'ONNX Runtime GPU Version': None,
  'ONNX Runtime Version': '1.19.0',
  'ONNX Version': '1.16.2',
  'OpenCV Contrib Python Headless Version': '4.10.0.84',
  'PyQt5 Version': '5.15.9'}

### Link to a Reproducible Demonstration Video

Didnt manage to reproduce

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
I understand that you encountered an error while labeling rectangular bounding boxes, and it seems to be due to a user action. Typically, when creating a Rectangle object, one needs to click on an initial point, then drag the mouse to the desired position, and finally click again to set the label properties in the tag manager before clicking OK to complete the creation.

If during the dragging process, the user switches to another mode without first releasing with the Esc key, this could cause a conflict. It's important to ensure that any changes or transitions between modes are done correctly to avoid such errors.

**Comment by jiangtangaaaa** [comment]
您好，我可能也遇到了类似的问题
1、点击矩形标注框后---标注---取消  ==> 标注存留在canvas
2、点击矩形标注框后---标注---取消---点击圆形标注--点击确定  ==> 变成矩形标注，而且标注框无法拖动
3、点击圆形----标注---点击取消---矩形标注---点击确定之后 == > 闪退

请问我该如何去修复或者规避这个问题呢

https://github.com/user-attachments/assets/973cbe62-42a6-41e3-a7c1-1d4d913a5ec2

**Comment by jiangtangaaaa** [comment]
@CVHub520 辛苦您解答

**Comment by CVHub520** [comment]
Hi, thank you for raising this issue!  

Regarding the first point, if you accidentally presses the cancel button while annotating, the same annotation box type should be restored for editing rather than starting a new annotation task. 

For example, if the user was drawing a rectangular box and canceled the operation, pressing the shortcut key (e.g., `R` for rectangle) should restore the drawing action. This behavior should apply to other annotation types as well.  

Let us know if you need further clarification!
