### ISSUE TITLE
用labelimg打的标签，无法载入到x-anyLabeling

### ISSUE THREAD

**Issue by XinZhenRen** [CVHub520/X-AnyLabeling#634]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

我的同事在他的电脑上完成框标注，当他发给我VOC的xml后。我选择”导入-》VOC检测框标签-》先择标签所在的文件夹“后，每个图片都会增加一个json文件，我知道这个json是x-anylabeling格式的信息文件，但会报错
![image](https://github.com/user-attachments/assets/30f06480-453c-47a0-a594-77a7ded30bdb)
是我操作有问题吗？谢谢您的答复！

**Comment by CVHub520** [comment]
Could you kindly send me the VOC annotation file along with the corresponding image files? If it’s convenient for you, please attach them to an email and send it to: cv_hub@163.com. Thank you in advance for your assistance.

**Comment by CVHub520** [comment]
The issue was caused by placing the XML label files in the same directory as the image files. To resolve the issue, separate the XML files from the image files into different directories and then import the labels again.

**Comment by wiekern** [comment]
> The issue was caused by placing the XML label files in the same directory as the image files. To resolve the issue, separate the XML files from the image files into different directories and then import the labels again.

Hi, I got a question for this feature, why the location of xml files need to be different to the image files? Since the past labelme projects keep the xml and image files in the same dir, now if I use this awesome tool to show/modify labels, I gotta do extra two steps as below:
1. create a folder
2.  move xml files to the new folder
This annoys me quite much, imagining that if the xml files is over 20w+, the two steps above are consuming lots of the time.
could u optimize it? if not, could u tell me where i can modify the code for sake of satisfying my needs.
