### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by XushaopengHNU** [CVHub520/X-AnyLabeling#645]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

我尝试导入我自己训练的yolov8关键点检测模型进行自动标注，但是报错“AttributeError: 'int' object has no attribute 'replace'”，以下是我自己训练好的onnx模型的输入输出信息以及我根据教程设置的yaml文件截图。
![onnx_lm](https://github.com/user-attachments/assets/219f261a-0199-406d-80c7-2cab5271eaa4)
![lm_yaml](https://github.com/user-attachments/assets/9e7c2de2-8fa9-44a9-add4-60101fa3e206)

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.4.3', 'Device': 'CPU'}

System Information:
    {'CPU': 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel',       
     'CUDA': None,
     'GPU': '0, NVIDIA GeForce RTX 3060, 12288',
     'Operating System': 'Windows-10-10.0.19045-SP0',
     'Python Version': '3.8.18'}

Package Information:
    {'ONNX Runtime GPU Version': '1.17.1',
     'ONNX Runtime Version': '1.17.1',
     'ONNX Version': '1.13.1',
     'OpenCV Contrib Python Headless Version': None,
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

https://www.bilibili.com/video/BV1Ves8ebEiP/?vd_source=bc0d8212c47d329c8a2b129199ffd8fd

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by XushaopengHNU** [comment]
我的yolov8关键点检测模型的标签为：框的标签：crosspoint，点的标签：1，每个矩形框中有一个点。

**Comment by CVHub520** [comment]
Thank you for bringing this to our attention. @XushaopengHNU

You're correct that purely numeric categories should be enclosed in quotes to prevent unintended conversion or parsing issues. For example, instead of using `1` as a category, it should be written as '1'.

This practice ensures that numeric categories are treated as strings and not mistakenly interpreted as numeric values by the system. 

If you encounter any other similar issues or have further questions, please don't hesitate to let me know.
