### ISSUE TITLE
Error in loading model: segment_anything_2_video with error: Torch not compiled with CUDAA enabled

### ISSUE THREAD

**Issue by Sade686** [CVHub520/X-AnyLabeling#647]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

ERROR   | model_manager:_load_model:1046 - ❌ Error in loading model: segment_anything_2_video with error: Torch not compiled with CUDAA enabled

**Comment by Sade686** [comment]
torch 2.4.1

**Comment by CVHub520** [comment]
Hey there! @Sade686,

Thank you for bringing this issue to our attention. The error message you provided indicates that the issue is not related to the model itself, but rather a problem with the configuration of your local PyTorch and CUDA environment.

I would suggest trying the following steps to resolve the problem:

1. Check the compatibility between the CUDA version installed on your system and the version required by the PyTorch library you are using. You can find the compatibility information online.

2. Try reinstalling or updating PyTorch and CUDA to ensure they are compatible and properly configured. You can refer to the PyTorch official documentation for installation guidelines.

3. If the above steps do not work, you can also try running the code in a fresh environment, such as a Docker container or a virtual environment.

Please let me know if you encounter any issues while trying these steps. I'll be happy to provide further assistance.

Best regards,
X-AnyLabeling Maintainer
