### ISSUE TITLE
Error in model prediction: [Errno 2] no such file or directory. Please check the model.

### ISSUE THREAD

**Issue by dep727** [CVHub520/X-AnyLabeling#649]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Model

### Bug

Error in model prediction: [Errno 2] no such file or directory: 'C:\\Users\\User\AppData\\Local\\Temp\\_MEI47002\\anylabeling\\services\\auto_labeling\\config/ppocr/ppocr_keys_v1.txt'. Please check the model.

### Information

Ran ch_PP-OCRv4 with X-Anylabeling-CPU.exe v2.4.3 
Found out that folder 'ppocr' does not exist when Temp folder got created every time executable open. I have to manually add ppocr folder from src code to that temp folder.

### Link to a Reproducible Demonstration Video

.

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hey there! @dep727,

Thank you for reporting this issue. I'm pleased to inform you that this bug has been fixed in the latest release.

The problem occurred because the 'ppocr' folder was not being properly included in the temporary folder when the executable was opened. This has been addressed in the latest commit

To resolve the issue, please redownload from the following [link](https://github.com/CVHub520/X-AnyLabeling/releases/tag/v2.4.3) and try it out.

If you encounter any further issues after updating, please don't hesitate to let us know. We appreciate your feedback as it helps us improve the software.
