### ISSUE TITLE
RAM++ labeling incorrectly

### ISSUE THREAD

**Issue by dunclaw** [CVHub520/X-AnyLabeling#657]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### Bug

When using the RAM++ model for labeling, it seems to be producing many incorrect labels.
I compared the labels generated by the .onnx version of the model to the labels generated by the latest version of the RAM plus model ram_plus_swin_large_14m.pth from the project page.
For the same image, the .onnx version used by X-AnyLabling is producing different (and largely incorrect) results compared to the latest .pth from the RAM release page. Was there some lossy process applied when converting to .onnx, or was a different model used?

### Information

Application Information:
    {'App name': 'X-AnyLabeling', 'App version': '2.4.3', 'Device': 'CPU'}

System Information:
    {'CPU': 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel',
     'CUDA': None,
     'GPU': '0, NVIDIA GeForce RTX 2080, 8192',
     'Operating System': 'Windows-11-10.0.22621-SP0',
     'Python Version': '3.12.4'}

Package Information:
    {'ONNX Runtime GPU Version': '1.19.2',
     'ONNX Runtime Version': '1.19.2',
     'ONNX Version': '1.16.1',
     'OpenCV Contrib Python Headless Version': '4.10.0.84',
     'PyQt5 Version': '5.15.7'}

### Link to a Reproducible Demonstration Video

https://1drv.ms/v/s!Ak22SaCaO4VottddS4tBxYRoOzrYvw?e=sZUaDm
Baseline RAM plus model generates correct tags for this image.

### Execution Mode

Source Code

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi @dunclaw,

Thank you for bringing this issue to our attention. It seems that there is a discrepancy in the labeling performance between the X-AnyLabeling (using ONNX runtime backend) and the PyTorch implementation.

To address this issue, we recommend implementing the model using the PyTorch backend and integrating it into X-AnyLabeling. This approach should help align the performance and accuracy between the two implementations.

If you are comfortable with PyTorch, you can follow these steps:
- Clone the X-AnyLabeling repository.
- Modify the backend to use PyTorch instead of ONNX runtime.
- Integrate the PyTorch model into the X-AnyLabeling pipeline.
- Test the performance and accuracy to ensure it aligns with the PyTorch implementation.

If you need further assistance with this process, please let us know, and we'll be happy to help.

Best regards,
X-AnyLabeling Maintainer

**Comment by CVHub520** [comment]
#352

**Comment by dunclaw** [comment]
That seems like a lot of work and a big change to the project. Perhaps there was just an issue in how you converted the RAM++ model to .onnx? Can you outline the steps you used for conversion? When I try to use torch.onnx.export or dynamo_export on the RAM++ checkpoint I get an export error.

**Comment by CVHub520** [comment]
@dunclaw Hey there! 

Thank you for pointing this out to us. I have fixed this bug, which was caused by the preprocessing procedure; I forgot to divide by 255 before. Now, you can update the source code and give it a try again!

Note that, although the bug has been fixed, there always exists some slight gap between the PyTorch and ONNX backends.

Finally, about how to export to ONNX format, the export method is very straightforward. You just wrap the model's forward function and use torch.onnx.export, and that should be good.
