### ISSUE TITLE
No module named 'anylabeling'

### ISSUE THREAD

**Issue by woshidamow5534** [CVHub520/X-AnyLabeling#665]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

No module named 'anylabeling'

### Additional

Traceback (most recent call last):
  File ".\app.py", line 21, in <module>
    from anylabeling.app_info import __appname__
ModuleNotFoundError: No module named 'anylabeling'
(x_anylabeling) PS F:\Great\X-AnyLabeling-2.3.1\anylabeling>

**Comment by CVHub520** [comment]
Hey there! @woshidamow5534,

Thank you for reporting this issue. The error you're encountering is due to the way you're trying to run the application. To resolve this, please follow these steps:

1. Open a terminal or command prompt.
2. Navigate to the root directory of the X-AnyLabeling project.
3. Run the following command:

   ```python
   python anylabeling/app.py
   ```

It's important to execute this command from the project's root directory, not from within the `anylabeling` folder. This ensures that Python can correctly locate and import all the necessary modules.

The error message you received ("No module named 'anylabeling'") suggests that you might have been inside the `anylabeling` directory when trying to run the script. This prevents Python from recognizing the `anylabeling` package structure correctly.

If you continue to experience issues after trying this, please let us know, and we'll be happy to provide further assistance.
