### ISSUE TITLE
issue "导出标签时发生错误 'type'"

### ISSUE THREAD

**Issue by jsrdcht** [CVHub520/X-AnyLabeling#667]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Export/Import

### Bug

When trying to export annotations in mask format, an error occurs, as shown in the image. There are no issues exporting segmentation annotations in VOC format.
![image](https://github.com/user-attachments/assets/07c5cd0a-6102-468b-9df1-b0da92e856f8)

### Information

Latest version of the exe

### Link to a Reproducible Demonstration Video

None

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Thank you for reporting this issue. 

To better assist you and get more detailed error information, I recommend running X-AnyLabeling from the source code instead of using the executable file. This approach will provide more comprehensive error messages, helping us to diagnose and resolve the problem more effectively.
