### ISSUE TITLE
How could I set an image as finished without any object labeled?

### ISSUE THREAD

**Issue by weathon** [CVHub520/X-AnyLabeling#678]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

About 50% of my images are empty and need to be labeled as "null"

**Comment by CVHub520** [comment]
To set an image as finished without any object labeled, you can simply check the checkbox next to the corresponding item in the file list box in the bottom right corner of the interface. This will mark the image as complete without requiring any object labels.

This approach allows you to efficiently handle empty images or those that don't require object labeling, while still marking them as processed in your dataset.

**Comment by BaoNguyen6742** [comment]
I'm using version 3.3.3 and the check box in the file list in the bottom right corner is not clickable. Can you looking into this please, thank you.

**Comment by CVHub520** [comment]
Hey there! @BaoNguyen6742 

Thank you for reporting this issue.  The checkboxes in the file list were not clickable because the `Qt.ItemIsUserCheckable` flag was missing when creating list items, even though `setCheckState()` was being called.

For now, we've added a configuration parameter `file_list_checkbox_editable` to control whether the checkboxes are editable. By default, it's set to `false` to maintain backward compatibility.

To make the checkboxes clickable, add the following to your `~/.xanylabelingrc` configuration file:

```yaml
file_list_checkbox_editable: true
```

After setting this, restart X-AnyLabeling and the checkboxes in the file list will be clickable.

The fix will be included in the next release. If you're building from source, you can pull the latest changes to get this fix immediately.

Thank you for your patience!

**Comment by Snag9311** [comment]
About images without annotations! I use train GUI from x-anylabeling, and even when I export negative sample as yolo format(empty txt file). The training load imgs uses data that has shape information only! I have OBB dataset and can't find the way to add nagative samples to the dataset.
