### ISSUE TITLE
我在导出yolo标签时候显示类别不在其中

### ISSUE THREAD

**Issue by magic-chai** [CVHub520/X-AnyLabeling#699]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

2024-10-31 21:14:18,837 | ERROR   | label_widget:export_yolo_annotation:4953 - Error occurred while exporting annotations: 'qilou' is not in list，实际上qilou就在我的classes.txt文件里面，这是为什么？

**Comment by CVHub520** [comment]
I apologize, but it seems the error is not due to the `classes.txt` file. The error message `label_widget_export_yolo_annotation:4953 - Error occurred while exporting annotations: 'qilou' is not in list` indicates that the `qilou` label is not present in the list of labels that the tool is expecting.

To resolve this, you will need to check the list of labels in the `classes.txt` file and ensure that all the required labels are correctly listed there. If the `qilou` label is indeed required, you will need to add it to the `classes.txt` file. Once you have updated the file with the proper labels, the tool should be able to export the annotations without that error.

Please let me know if you have any other questions!

**Comment by magic-chai** [comment]
感谢，我知道问题所在了，class.txt文件里面我多打了空格
