### ISSUE TITLE
请问可以指定服务器中的某一个GPU进行加速吗？

### ISSUE THREAD

**Issue by junjundaidai** [CVHub520/X-AnyLabeling#701]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

现想在linux服务器中运行X-AnyLabeling, 服务器有多个GPU(device=0, device=1 等)，
看到app_info.py中说，想让GPU加速只需将CPU改成GPU即可，所以想请问要是想指定一个GPU（例如 指定 device=2）来加速的话，该在哪里修改代码呀？谢谢！

**Comment by CVHub520** [comment]
```bash
CUDA_VISIBLE_DEVICES=2 python anylabeling/app.py
```

**Comment by junjundaidai** [comment]
@CVHub520

感谢回复！ 刚试了一下好像还是没有用上GPUㅠ 我再试试！！

还想请教一个问题，或许X-AnyLabeling支持在Docker容器中运行吗？ 例如在docker中安装conda环境运行这样子

**Comment by CVHub520** [comment]
@junjundaidai Hello! 

In response to your question, I suggest handling it in the following steps:
- First, please ensure that you have correctly installed all dependencies according to the official documentation (https://github.com/CVHub520/X-AnyLabeling/blob/main/docs/zh_cn/get_started.md), paying special attention to ensuring that the version of onnxruntime-gpu matches your local environment (CUDA version, etc.).
- To help troubleshoot the issue, please run the diagnostic script below and provide the output results:

```bash
python anylabeling/checks.py
```

This way we can understand your specific environmental settings better and assist you more effectively.

Regarding Docker environment issues: X-AnyLabeling can indeed be run in Docker, but you need to write a Dockerfile suitable for your own environment, including properly configuring CUDA environments, conda environments, etc. It is recommended to refer to the official documentation's dependency requirements when writing the Dockerfile.

If there are still problems after running the diagnostic script, please provide the output results so that we can further assist with troubleshooting.

**Comment by junjundaidai** [comment]
@CVHub520 WOWWW~ Thank you so much for your reply !!!  I'll tell you the process of docker setting soon!!!!!

**Comment by junjundaidai** [comment]
> @CVHub520 WOWWW~ Thank you so much for your reply !!! I'll tell you the process of docker setting soon!!!!!

将X-Anylabeling在docker中进行配置的计划可能要被耽搁了55 抱歉，如果后续有机会做docker的话，我会继续在此处更新内容的！！！谢谢！！！

**Comment by CVHub520** [comment]
This issue will be temporarily closed. If there are any updates, plz reopen the issue or start a new one.
