### ISSUE TITLE
建议增加任意顶点四边形的导出

### ISSUE THREAD

**Issue by YellowThree-HS** [CVHub520/X-AnyLabeling#705]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

因为yolo11-obb是支持任意顶点四边形的，但是当我画完之后，只能导出旋转矩形框，而没办法导出四边形的标注
这是格式：
class_index x1 y1 x2 y2 x3 y3 x4 y4

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Thank you for your feature request. For the case of an arbitrary quadrilateral, I would recommend using a polygon object instead of rotation. The polygon object is better suited for handling arbitrary quadrilateral shapes since it can define any four-point shape without being constrained by rotation parameters.

In X-AnyLabeling, you can achieve this with the polygon annotation, which gives you more flexibility to mark any four-sided shape regardless of its orientation or regularity. This would be more appropriate than trying to extend the rotation feature for this use case.

**Comment by YellowThree-HS** [comment]
对，我用四边形画的，但是导出的时候无法导出yolo格式，直接是空白的txt，只有标注旋转矩形框的时候才能导出yolo格式。
所以最后我自己写了一个脚本，根据你默认的json文件生成yolo格式

**Comment by CVHub520** [comment]
![image](https://github.com/user-attachments/assets/df57fe0c-b6f8-46dc-9e00-dbb3934547ca)

**Comment by YellowThree-HS** [comment]
噢噢get了，thank you!
