### ISSUE TITLE
Error in predict_shapes: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by 123456-sire** [CVHub520/X-AnyLabeling#706]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

I used onnx exported by mmyolo and got the following bug after importing: model_manager:predict_shapes:2099 - Error in predict_shapes: zero-size array to reduction operation maximum which has no identity

**Comment by CVHub520** [comment]
Hi @123456-sire,

Since `mmYOLO` is a custom model rather than a built-in one, it may have compatibility issues when integrated with X-AnyLabeling. Here are some steps to troubleshoot:

1. **Check Model Output Shape**: Ensure the output shape of the `mmYOLO` ONNX model matches the expected input requirements in X-AnyLabeling’s `predict_shapes` function. Mismatched shapes can lead to empty arrays in certain operations, causing the "zero-size array" error.

2. **Input and Output Configuration**: Confirm that the input preprocessing and output post-processing are configured correctly. A mismatch here could cause the model to output unexpected shapes or empty arrays.

3. **Compatibility with ONNX Runtime**: Verify that your ONNX runtime version supports all operations in `mmYOLO`. Custom models might rely on operations that require specific ONNX runtime versions or configurations.

If these suggestions don’t resolve the issue, could you provide more information on the model configuration and any custom preprocessing steps? This would help in providing more specific guidance.

Hope this helps!
