### ISSUE TITLE
批量标注修改是否支持从文件夹下某张图片到某张图片这一段的替换？

### ISSUE THREAD

**Issue by nidetaoge** [CVHub520/X-AnyLabeling#708]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

同一个文件夹下的图片，例如一个人戴hat，后来戴helmet，但是同一个提示词hat批量标注后可能同时将这两者标出来，这时候希望中间某个片段批量修改标签hat成helmet，但不是整体全部替换。

**Comment by CVHub520** [comment]
@nidetaoge, Hi!

Thank you for your query. The range selection feature for label modification has been implemented. You can now specify a range (From/To) in the Label Change Manager to modify labels for specific segments of your dataset instead of applying changes globally.

Please let me know if you have any questions.
