### ISSUE TITLE
标注时切换图形

### ISSUE THREAD

**Issue by jiangtangaaaa** [CVHub520/X-AnyLabeling#717]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar bug report.

### X-AnyLabeling Component

Tool

### Bug

您好，我可能也遇到了类似的问题 [#630](https://github.com/CVHub520/X-AnyLabeling/issues/630)
1、点击矩形标注框后---标注---取消 ==> 标注存留在canvas
2、点击矩形标注框后---标注---取消---点击圆形标注--点击确定 ==> 变成矩形标注，而且标注框无法拖动
3、点击圆形----标注---点击取消---矩形标注---点击确定之后 == > 闪退
我点击esc并没有取消选择

请问我该如何去修复或者规避这个问题呢

### Information

assert len(self.points) in [1, 2]
AssertionError

### Link to a Reproducible Demonstration Video

https://github.com/user-attachments/assets/2e360486-3d95-4951-8793-32f88b92b803

### Execution Mode

Pre-compiled Executable

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
Hi, thank you for raising this issue!

Regarding the first point, if a user accidentally presses the cancel button while annotating, the same annotation box type should be restored for editing rather than starting a new annotation task. 

For example, if you was drawing a rectangular box and canceled the operation, pressing the shortcut key (e.g., `R` for rectangle) should restore the drawing action. This behavior should apply to other annotation types as well.

Let us know if you need further clarification!
