### ISSUE TITLE
什么时候能支持图片或视频文本描述任务?

### ISSUE THREAD

**Issue by congjianting** [CVHub520/X-AnyLabeling#725]
### Search before asking

- [X] I have searched the X-AnyLabeling [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar feature requests.

### Description

图片的文本描述支持?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CVHub520** [comment]
@congjianting, Hi; Thank you for your feature request! 🙌 

Supporting text description tasks for images or videos is a great idea, and I understand its importance. However, due to current time and resource constraints; I won’t be able to prioritize this feature immediately.

That said, it’s on my radar, and I anticipate being able to work on it in the coming months. Stay tuned, and feel free to share any additional input in the meantime! 🚀
