### ISSUE TITLE
一次运行所有图片时, 若使用GPU加速, 最快能跑到多快(5张/秒, 10张/秒, 25张/秒)?

### ISSUE THREAD

**Issue by chevydream** [CVHub520/X-AnyLabeling#757]
### Search before asking

- [X] I have searched the X-AnyLabeling [Docs](https://github.com/CVHub520/X-AnyLabeling/tree/main/docs) and [issues](https://github.com/CVHub520/X-AnyLabeling/issues) and found no similar questions.

### Question

一次运行所有图片时, 我的1080Ti占用率只有2%, 而且显示界面会显示每一张图片和框, 整体感觉并未加速多少
能否: 采用Batch模式, 或多张图并行推理, 或者推理时不进行界面显示, 总之将速度提升上去, 充分利用GPU性能

**Comment by CVHub520** [comment]
Please try using a more powerful GPU, as the computing power of a 1080Ti is clearly outdated for modern deep learning models.

**Comment by chevydream** [comment]
我测试了一下在1080Ti下使用onnxRunTime加速推理的耗时, 如下图所示
![1735034328656](https://github.com/user-attachments/assets/8c635d47-6e4b-46ad-9f57-358c202e6603)
![1735034431954](https://github.com/user-attachments/assets/8d84a294-f79d-4acb-a14a-85de2e101933)
从图中可以看出, 推理耗时只有十几毫秒, 但程序的整体运行速度只有5张/秒左右, 差距很大, 时间应该是消耗在程序的调度上了, 我的意思是能否对程序的调度进行优化, 比如: 采用Batch模式, 或多张图并行推理, 或者推理时不进行界面显示, 总之将速度提升上去, 充分利用GPU性能

**Comment by chevydream** [comment]
最佳的方案是: 在执行【一次运行所有图片】任务时, 只执行: 图片加载, 模型推理, 标签输出三个步骤, 其它都不执行

**Comment by CVHub520** [comment]
I apologize for the inconvenience caused by this performance issue. It appears there's a bug affecting larger image sets, and I understand how frustrating that can be.

In the meantime, please avoid loading a large number of images at once. For instance, limit the batch size to around 2,000 images per load, depending on your CPU's processing capacity. It's recommended to start with smaller batches, such as 200 images, to see if there's a noticeable improvement in inference speed.

Lastly, please note that the current software has significant performance degradation when handling a large number of files. Thank you for your understanding.

**Comment by chevydream** [comment]
知道是哪里耗时大了, 时间主要消耗在图片的加载和转换上了
![1735102773988](https://github.com/user-attachments/assets/e9371641-d0a9-4a4f-8a9c-5e2c9eb38451)

**Comment by chevydream** [comment]
测试发现: 推理时, 无需调用load_file函数, 只要调用其中四句就行了; 另外, 也不需要调用progress_dialog.setValue()函数. 通过注释掉这两个函数, 推理速度可提升到 25张/秒, 基本满足我的需求了.	
![1735180659645](https://github.com/user-attachments/assets/0704ceb9-2b90-412a-9da5-39b108925861)

**Comment by CVHub520** [comment]
Woo...! Thank you for sharing this fantastic optimization insight! The improvement to 25 fps is truly impressive. We would be very grateful if you could submit a PR with these changes - it would benefit many users in the community. Please feel free to create a branch and submit the PR, and we'll prioritize its review. Thanks again for your valuable contribution!
