### ISSUE TITLE
打开视频文件加载完毕后没有变化，再次打开视频文件也不再加载

### ISSUE THREAD

**Issue by wpNZC** [CVHub520/X-AnyLabeling#80]

**Comment by CVHub520** [comment]
您好，麻烦将测试视频打包发送至邮箱: cv_hub@163.com，我这边复现下。

**Comment by CVHub520** [comment]
已解决，使用旧版本不支持视频解析。

**Comment by yu1chaofan** [comment]
X-AnyLabeling-CPU-2.3.0.exe  还是有这个问题,X-AnyLabeling处理完视频就不显示了

**Comment by CVHub520** [comment]
Thank you for your feedback. We acknowledge the issue with the program X-AnyLabeling not displaying any video after processing. It seems the issue is related to the presence of Chinese characters in the file path. We've taken your observation into account and have added a feature reminder for selecting paths without using Chinese characters.

**Comment by smallboy-code** [comment]
> Thank you for your feedback. We acknowledge the issue with the program X-AnyLabeling not displaying any video after processing. It seems the issue is related to the presence of Chinese characters in the file path. We've taken your observation into account and have added a feature reminder for selecting paths without using Chinese characters.

C:\Users\Administrator\Desktop\X-AnyLabeling-main\assets我在这个路径下也打开不了，我用的是源码编译，2.3.5
